# Default configuration for NGC-AKI pipeline
# NOTE: override any field in experiment YAML via `extends: base.yml`.

paths:
  raw_dir: Input/raw/
  processed_dir: Input/processed/
  sql_output_dir: Input/raw/

sql:
  enabled: true
  psql_bin: psql
  # If $MIMIC_DB_CONN is set, the conn block may be omitted
  conn:
    host: localhost
    port: 5432
    user: postgres
    db: mimiciv
  script: Libs/Data/SQL/run.sql

preprocess:
  enabled: true
  resample_horizon: 24

model:
  backbone: cMLP
  lag: 24
  hidden: [128, 64]
  training:
    optimizer: gista
    max_iter: 5000
    lr: 1e-3
    lam: 1e-2
    lam_ridge: 1e-3
    penalty: H
    batch_size: 32

# ---- duplicate lines removed ----

# paths placeholder removed

# paths:
#  