extends:
  - base.yml
  - model.yml

# Only override what is different from the defaults

sql:
  enabled: false  # Skip SQL extraction for this local run

model:
  training:
    max_iter: 2000   # override default
    batch_size: 64

device: cuda:3      # cuda | cpu | cuda:id etc.
seed: 42
