extends:
  - base.yml
  - model.yml

# Only override what is different from the defaults

sql:
  enabled: false  # Skip SQL extraction for this local run

model:
  training:
    max_iter: 2000   # override default
    batch_size: 256

device: cuda:3      # cuda | cpu | cuda:id etc.
seed: 42

processed_dir: Input/processed/
resample_horizon: 24               # hours
min_records: 4                    # minimum hourly rows per patient
